# fly.toml file generated for materials-catalog on 2023-05-16T22:14:58-04:00

app = "materials-catalog"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "bos"
processes = []

[build]
  [build.args]
    NEXT_PUBLIC_MONGODB_URI='mongodb+srv://nonAdmin:nonAdminPassword123@cluster0.rzxoox5.mongodb.net/materialDemo?retryWrites=true&w=majority'

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
